name: board_game_arena

channels:
  - conda-forge
  - nvidia
  - pytorch

dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - numpy
  - pyyaml  
  - pip:
      - ray
      - open-spiel
      - litellm
      - ffmpy
      - gradio
      - transformers
      - python-dotenv
      - argparse
      - tensorboard
