# API Provider Configuration
# Maps provider names to their corresponding environment variable names

providers:
  groq:
    api_key_env: "GROQ_API_KEY"
    description: "Groq API for fast inference"

  together:
    api_key_env: "TOGETHER_API_KEY"
    description: "Together AI API"

  fireworks:
    api_key_env: "FIREWORKS_API_KEY"
    description: "Fireworks AI API"

  openai:
    api_key_env: "OPENAI_API_KEY"
    description: "OpenAI API"

  anthropic:
    api_key_env: "ANTHROPIC_API_KEY"
    description: "Anthropic Claude API"

  cohere:
    api_key_env: "COHERE_API_KEY"
    description: "Cohere API"

  google:
    api_key_env: "GOOGLE_API_KEY"
    description: "Google AI API"

  mistral:
    api_key_env: "MISTRAL_API_KEY"
    description: "Mistral AI API"

  replicate:
    api_key_env: "REPLICATE_API_KEY"
    description: "Replicate API"

# Configuration options
config:
  # Default naming convention for new providers
  default_env_pattern: "{PROVIDER}_API_KEY"

  # Whether to auto-generate environment variable names
  auto_generate_env_names: true
