# Debug config for illegal move detection
env_configs:
  - game_name: matrix_rps
    max_game_rounds: null

num_episodes: 1
seed: 42
use_ray: false
mode: llm_vs_random

agents:
  player_0:
    type: llm
    model: litellm_groq/llama3-8b-8192
  player_1:
    type: random

llm_backend:
  max_tokens: 250
  temperature: 0.1
  default_model: litellm_groq/llama3-8b-8192

log_level: DEBUG
